In [11]:
import ufc_scrap as ufc
import numpy as np

In [13]:
df_events = ufc.get_events()

df_events

WARNING:Webscraping Realizado

,event_id,event,date,city,state,country
0,EVE0664,UFC Fight Night: Fiziev vs. Gamrot,2023-09-23,Las Vegas,Nevada,USA
1,EVE0663,UFC Fight Night: Grasso vs. Shevchenko 2,2023-09-16,Las Vegas,Nevada,USA
2,EVE0662,UFC 293: Adesanya vs. Strickland,2023-09-09,Sydney,New South Wales,Australia
3,EVE0661,UFC Fight Night: Gane vs. Spivac,2023-09-02,Paris,Ile-de-France,France
4,EVE0660,UFC Fight Night: Holloway vs. The Korean Zombie,2023-08-26,Kallang,NaN,Singapore
...,...,...,...,...,...,...
659,EVE0005,UFC 6: Clash of the Titans,1995-07-14,Casper,Wyoming,USA
660,EVE0004,UFC 5: The Return of the Beast,1995-04-07,Charlotte,North Carolina,USA
661,EVE0003,UFC 4: Revenge of the Warriors,1994-12-16,Tulsa,Oklahoma,USA
662,EVE0002,UFC 3: The American Dream,1994-09-09,Charlotte,North Carolina,USA
663,EVE0001,UFC 2: No Way Out,1994-03-11,Denver,Colorado,USA

In [10]:
df_fights = ufc.get_fights()

df_fights

WARNING:Webscraping não realizado

,event_id,weight_class,w/l,fighter1,fighter2,kd_fighter1,kd_fighter2,str_fighter1,str_fighter2,td_fighter1,td_fighter2,sub_fighter1,sub_fighter2,method,round,time
0,EVE0663,Women's Flyweight,draw,Alexa Grasso,Valentina Shevchenko,1,0,84,80,1,4,1,1,S-DEC,5,5:00
1,EVE0663,Welterweight,win,Jack Della Maddalena,Kevin Holland,0,0,105,127,0,0,0,0,S-DEC,3,5:00
2,EVE0663,Bantamweight,win,Raul Rosas Jr.,Terrence Mitchell,1,0,18,6,0,0,0,0,KO/TKO_Punches,1,0:54
3,EVE0663,Lightweight,win,Daniel Zellhuber,Christos Giagos,0,0,36,38,0,0,1,0,SUB_Anaconda_Choke,2,3:26
4,EVE0663,Featherweight,win,Kyle Nelson,Fernando Padilla,0,0,82,72,0,0,0,0,U-DEC,3,5:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7335,EVE0001,Open Weight,win,Orlando Wiet,Robert Lucarelli,0,0,8,2,0,1,0,1,KO/TKO,1,2:50
7336,EVE0001,Open Weight,win,Frank Hamaker,Thaddeus Luster,0,0,2,0,1,0,3,0,SUB_Keylock,1,4:52
7337,EVE0001,Open Weight,win,Johnny Rhodes,David Levicki,0,0,11,4,1,0,0,0,KO/TKO_Punches,1,12:13
7338,EVE0001,Open Weight,win,Patrick Smith,Ray Wizard,0,0,1,1,0,0,1,0,SUB_Guillotine_Choke,1,0:58
7339,EVE0001,Open Weight,win,Scott Morris,Sean Daugherty,0,0,1,0,1,0,1,0,SUB_Guillotine_Choke,1,0:20

In [14]:
df_fighters = ufc.get_fighters()

df_fighters

WARNING:Webscraping não realizado

,First,Last,Nickname,Stance,Belt,height,reach,weight,win,lose,draw,total_fights,fighters_id
0,Tom,Aaron,NaN,NaN,NaN,NaN,NaN,70.307,5,3,0,8,FIG3286
1,Danny,Abbadi,The Assassin,Orthodox,NaN,180.34,NaN,70.307,4,6,0,10,FIG2942
2,Nariman,Abbasov,Bayraktar,Orthodox,NaN,172.72,167.64,70.307,28,4,0,32,FIG0482
3,David,Abbott,Tank,Switch,NaN,182.88,NaN,120.202,10,15,0,25,FIG0923
4,Hamdy,Abdelwahab,The Hammer,Southpaw,NaN,187.96,182.88,119.748,5,0,0,5,FIG3664
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4104,Dave,Zitanick,NaN,NaN,NaN,NaN,NaN,77.111,5,7,0,12,FIG2609
4105,Alex,Zuniga,NaN,NaN,NaN,NaN,NaN,65.771,6,3,0,9,FIG3121
4106,George,Zuniga,NaN,NaN,NaN,175.26,NaN,83.915,3,1,0,4,FIG3843
4107,Allan,Zuniga,Tigre,Orthodox,NaN,170.18,177.80,70.307,13,1,0,14,FIG2267
4108,Virgil,Zwicker,RezDog,NaN,NaN,187.96,187.96,92.986,15,6,1,22,FIG1259